# Data Loading, Strorage and file formats
DataFrame

In [1]:
import pandas as pd

In [2]:
data={
    "Name":["Amit","Riya","Rahul","Priya","Karan"],
    "Age":[20,21,20,22,21],
    "Department":["CSE","IT","CSE","ECE","IT"],
    "Marks":[85,90,78,88,76]
}
df=pd.DataFrame(data)
df

    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

# include 5 more rows in the dataframe
convert to differnt file formats and
compare the file size

In [33]:
data={
    "Name":["Amit","Riya","Rahul","Priya","Karan","Mayank","Kiran","Ramu","Neha","Mahi"],
    "Age":[20,21,20,22,21,22,23,21,24,22],
    "Department":["CSE","IT","CSE","ECE","IT","CSE","IT","CSE","ECE","IT"],
    "Marks":[85,90,78,88,76,85,90,78,88,76]
}
df=pd.DataFrame(data)
df

     Name  Age Department  Marks
0    Amit   20        CSE     85
1    Riya   21         IT     90
2   Rahul   20        CSE     78
3   Priya   22        ECE     88
4   Karan   21         IT     76
5  Mayank   22        CSE     85
6   Kiran   23         IT     90
7    Ramu   21        CSE     78
8    Neha   24        ECE     88
9    Mahi   22         IT     76

In [37]:
# CSV format
df.to_csv("student_csvoutput.csv", index=False)
student_csv = pd.read_csv("student_csvoutput.csv")
print("CSV Output:")
print(student_csv.head())

CSV Output:
    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

In [38]:
# Excel format
df.to_excel("student_exceloutput.xlsx", index=False)
student_excel = pd.read_excel("student_exceloutput.xlsx")
print("\nExcel Output:")
print(student_excel.head())

Excel Output:
    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

In [39]:
# JSON format
df.to_json("student_jsonoutput.json", orient="records", indent=4)
student_json = pd.read_json("student_jsonoutput.json")
print("\nJSON Output:")
print(student_json.head())

JSON Output:
    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

In [40]:
# Parquet format
df.to_parquet("student_parquetoutput.parquet", index=False)
student_parquet = pd.read_parquet("student_parquetoutput.parquet")
print("\nParquet Output:")
print(student_parquet.head())

Parquet Output:
    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

In [41]:
# Compare file sizes
files = [
    "student_csvoutput.csv",
    "student_exceloutput.xlsx",
    "student_jsonoutput.json",
    "student_parquetoutput.parquet"
]

print("\nFile Size Comparison:")
for file in files:
    size = os.path.getsize(file)
    print(f"{file}: {size} bytes")

File Size Comparison:
student_csvoutput.csv: 178 bytes
student_exceloutput.xlsx: 5209 bytes
student_jsonoutput.json: 1014 bytes
student_parquetoutput.parquet: 2873 bytes

In [11]:
# Inspect the DataFrame
print("shape of the data frame:\n",df.shape)
print("the top three rows:\n",df.head(3))
print("the last two rows:\n",df.tail(2))
print("columns :\n",df.columns.tolist)
print("data type of each column:\n",df.dtypes)
print("information:\n",df.info())
print("Statistics of the data frame :\n",df.describe())

shape of the data frame:
 (5, 4)
the top three rows:
     Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
the last two rows:
     Name  Age Department  Marks
3  Priya   22        ECE     88
4  Karan   21         IT     76
columns :
 <bound method IndexOpsMixin.tolist of Index(['Name', 'Age', 'Department', 'Marks'], dtype='object')>
data type of each column:
 Name          object
Age            int64
Department    object
Marks          int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
information:
 None
Statistics of the data frame :
             Age     Marks
count   5.00000   5.00000
mean   20.80000  83.40000
std     0.83666   6.14817
min    20.00000  76.00000
25%    20.00000  78.00000
50%    21.00000  85.00000
75%    21.00000  88.00000
max    22.00000  90.00000

In [12]:
iris=pd.read_csv("/content/Iris.csv")
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
print(iris.shape)
print(iris.columns)
print(iris.dtypes)

(150, 6)
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

# File Formats
1. csv
2. excel
3. json
4. parquet

In [19]:
#load the data set in file format
iris.to_csv("iris_csvoutput.csv",index=False)
# read the sved dataset
iris_csv=pd.read_csv("/content/iris_csvoutput.csv")
print(iris_csv.head)

<bound method NDFrame.head of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [22]:
iris.to_excel("iris_exceloutput.xlsx",index=False)
# load
iris_excel=pd.read_excel("/content/iris_exceloutput.xlsx")
print(iris_excel.tail(10))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4
141  142            6.9           3.1            5.1           2.3
142  143            5.8           2.7            5.1           1.9
143  144            6.8           3.2            5.9           2.3
144  145            6.7           3.3            5.7           2.5
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
140  Iris-virginica
141  Iris-virginica
142  Iris-virginica
143  Iris-virginica
144  Iris-virginica
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

In [24]:
# json file format
iris.to_json("iris_jsonoutput.json",orient="records",indent=4)
#read the file
iris_json=pd.read_json("/content/iris_jsonoutput.json")
print(iris_json.head(5))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [27]:
# file format parquet
iris.to_parquet("iris_parquetoutput.parquet",index=False)
# read
iris_parquet = pd.read_parquet("/content/iris_parquetoutput.parquet")
print(iris_parquet.head(3))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [29]:

# Compare the size of file formats
import os

files = [
    "iris_csvoutput.csv",
    "iris_exceloutput.xlsx",
    "iris_jsonoutput.json",
    "iris_parquetoutput.parquet"
]

for file in files:
    size = os.path.getsize(file)
    print(f"{file} : {size} bytes")

iris_csvoutput.csv : 5107 bytes
iris_exceloutput.xlsx : 9207 bytes
iris_jsonoutput.json : 26794 bytes
iris_parquetoutput.parquet : 5932 bytes

In [31]:
# load the selected columns
iris_small=pd.read_csv("/content/Iris.csv",usecols=["SepalLengthCm","SepalWidthCm","Species"])
iris_small.head(3)

   SepalLengthCm  SepalWidthCm      Species
0            5.1           3.5  Iris-setosa
1            4.9           3.0  Iris-setosa
2            4.7           3.2  Iris-setosa

In [32]:
#filter the data
result=iris[iris["SepalLengthCm"]>6]
result.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor